document.write ('<table>');
document.write ('<tr>');
document.write ('<td align="center"><marquee style="word-break:break-all;FONT-SIZE: 9pt; LEFT: 2px; MARGIN-LEFT: 2px; WIDTH: 100%; TOP: 2px; HEIGHT: 100px; TEXT-ALIGN: center" onMouseOver=this.stop() onMouseOut=this.start() scrollamount=1 scrolldelay=50 direction=up behavior=loop>');
document.write ('<a href="http://www.nbarticle.com/" target=_blank title="NB文章系统(NBArticle)是由原NB联盟一部分成员经过几年的开发经验积累而成的一个高效、简洁、安全的文章系统，无任何多余累赘的功能，而且与MS SQL Server结合，更能发挥更好的效果。"><img src="http://www.nbarticle.com/images/nbarticle.gif" align="absmiddle" width="88" height="31" src="NB文章系统(NBArticle)是由原NB联盟一部分成员经过几年的开发经验积累而成的一个高效、简洁、安全的文章系统，无任何多余累赘的功能，而且与MS SQL Server结合，更能发挥更好的效果。"></a><br>');
document.write ('</marquee></td>');
document.write ('</tr>');
document.write ('<tr><td align="center" height="5"></td></tr>');
document.write ('<tr><td align="center">');
document.write ('<select name="textfriend" onChange="if(this.selectedIndex) window.open(this.options[this.selectedIndex].value);" style="width:150">');
document.write ('<option value="">--文字连接站点--</option>');
document.write ('<option value="http://www.nbarticle.com/">NB文章系统官方站</option>');
document.write ('</select></td>');
document.write ('</tr>');
document.write ('<tr><td align="center" height="5"></td></tr>');
document.write ('<tr><td align="center" height="25"><a href="#" onclick="javascript:window.open(\'/NBArticle/NBArticle/app_link.asp\',\'\',\'height=320,width=550\')">申请连接</a>&nbsp;&nbsp;<a href="/NBArticle/NBArticle/morelink.asp" target="_blank">更多连接</a></td>');
document.write ('</tr>');
document.write ('</table>');
